navbar_title = 'Yusuf Aktepe'
footer = "Copyright © 2019-2024 by Yusuf Aktepe"
author = "Yusuf Aktepe"
color_scheme = "dark"

enable_zooming_js = true
enable_toc = false
enable_site_search = true
enable_math = false

comments = true

# SEO
enable_open_graph = true
enable_twitter_cards = true

# Collapsible Menu
enable_collapsible_toc = true
enable_collapsible_changelogs = true

[list_layout]
enable_group_by_year = true
enable_show_date = true
enable_pagination = false

# syntax highlight settings
[syntax_highlight]
lib = "prism.js" # "builtin" | "prism.js"

    [syntax_highlight.builtin]
    enable_code_copy = true

    [syntax_highlight.prism]
    enable_code_copy = true
    enable_line_no = false
